apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: torwei-nginx-webapp
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: manifests/nginx-webapp
    repoURL: https://github.com/tor-wei/argocd-guestbook.git
    targetRevision: HEAD
  destination:
    namespace: torwei-ns
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
