# minimal, safe customizations — keep everything else as pulled
replicaCount: 2

service:
  type: ClusterIP  # use NodePort/LoadBalancer only if your cluster supports it

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi